# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  repository_dispatch:
    types: [run_pages_deploy]
    
  workflow_dispatch:
  
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - master
      - bot


  

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Switch branch
        run: |
          git fetch origin master
          git checkout master
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './src/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
